### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by seajaysec** [giovannicoppola/alfred-phoneticSpelling#3]
https://github.com/giovannicoppola/alfred-phoneticSpelling/assets/7016191/4f60786d-2b6d-4207-a6f2-528734d23848

I've made my trigger `%` and have made no other modifications. This doesn't seem to work, unless I'm not understanding how to trigger it. My expectation is that after entering the trigger I'd be able to type the word I want phonetically spelled.

**Comment by giovannicoppola** [comment]
Thanks for reporting @seajaysec. For some reason for some users there's an issue with the custom dictionary file. It should be fixed in [this version](https://github.com/giovannicoppola/alfred-phoneticSpelling/releases/download/v1.3/Phonetic.Spelling1.3.alfredworkflow) (or, if you installed from the Gallery, it should update in 1-2 days). Let me know if you run into problems!

**Comment by seajaysec** [comment]
Fantastic, that works! Thanks.
